name = "ProbabilityThing"
uuid = "1b4270de-f850-498e-83de-ccc7e5f1f9e4"
authors = ["Luisa Orozco <l.orozco@esciencecenter.nl> and contributors"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
